services:
  - type: web
    name: nova-web
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: /api/plans
    autoDeploy: true
    envVars:
      - key: JWT_SECRET
        value: nova-render-jwt-CHANGE-2026
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
